name = "a5396266-bd87-49b4-b6d1-cb8fe0616365"
account_id = "6ec57290cbb52c27cda0bd089bae05a0"
compatibility_date = "2024-01-01"
main = "functions/index.ts"
usage_model = "bundled"

[site]
bucket = "./public"

[env.production]
workers_dev = true